# Generated by Django 3.2.13 on 2022-12-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prize', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
