# Generated by Django 3.2.13 on 2023-02-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('is_album', models.BooleanField(default=False)),
                ('album_title', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('song_type', models.CharField(blank=True, choices=[('OR', 'Original'), ('CV', 'Cover'), ('RM', 'Remix')], max_length=2, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
