# Generated by Django 3.2.13 on 2023-02-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerUi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_album',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
