# Generated by Django 3.2.13 on 2023-02-18 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playerUi', '0002_alter_song_is_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='country',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='audio_files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
